name: CI - Build & Push Docker Images

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_NAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build & Push Docker Images
              run: |
                  # Build Svelte frontend
                  docker build -t ${{ secrets.DOCKER_NAME }}/bill-share:latest ./web
                  docker push ${{ secrets.DOCKER_NAME }}/bill-share:latest
