name: CI - Build & Push Docker Image

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_NAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build & Push Multi-Arch Docker Image
              run: |
                  docker buildx build --platform linux/arm64 --build-arg DATABASE_URL=${{secrets.DATABASE_URL}} -t ${{ secrets.DOCKER_NAME }}/bill-share:latest .
