name: CI - Build & Push Docker Images

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build & Push Docker Images
              run: |
                  docker login -u ${{ secrets.DOCKER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  docker build -t ${{ secrets.DOCKER_NAME }}/bill-share:latest ./web
                  docker push ${{ secrets.DOCKER_NAME }}/bill-share:latest
